[package]
name = "anthovai-retrieval"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anthovai-core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
chrono.workspace = true
tracing.workspace = true
metrics.workspace = true
utoipa.workspace = true
async-trait.workspace = true
anthovai-embeddings.workspace = true
sqlx.workspace = true
anthovai-db.workspace = true
pgvector.workspace = true

[dev-dependencies]
anthovai-testkit.workspace = true
anthovai-ingestion.workspace = true
anthovai-knowledge.workspace = true
anthovai-storage.workspace = true
tokio.workspace = true
anthovai-provider-openai.workspace = true
